name: hpr-api-route
services:
  api-route-go:
    container_name: hpr-api-route
    build: .
    ports:
      - "5737:8081"
    security_opt:
      - apparmor:unconfined
    networks:
      - hpradar-net

networks:
  hpradar-net:
    external: true

